language: python
matrix:
  include:
  - python: 3.6
  - python: 3.7
  - python: 3.8
    sudo: true
    dist: xenial
install:
- pip install --upgrade .[qiskit,projectq,dev] coveralls
env:
- API_URL=https://staging.quantum-inspire.com
script:
- echo "running unit tests"
- coverage run --source="./src/quantuminspire" -m unittest discover -s src/tests -t src -v
- echo "running mypy"
- MYPYPATH=./src mypy --strict --ignore-missing-imports -p quantuminspire
- echo "running pylint"
- pylint quantuminspire || true
- echo "running examples"
- python ./docs/example_projectq_entangle.py
- python ./docs/example_projectq_grover.py
- python ./docs/example_qiskit_entangle.py
- echo "running notebooks"
- jupyter nbconvert --to notebook --execute --ExecutePreprocessor.timeout=300 docs/example_projectq.ipynb
- jupyter nbconvert --to notebook --execute --ExecutePreprocessor.timeout=300 docs/grover_algorithm_qi.ipynb
- jupyter nbconvert --to notebook --execute --ExecutePreprocessor.timeout=300 docs/qi-performance-test.ipynb
after_success:
- coveralls
deploy:
  provider: pypi
  user: qinspire
  password:
    secure: LN2iXxsoffIVmLKBuX6z273D1PpJt6zYLLF3snfkM4lzQZhNl4nLn/D0CdMb0OiMAKINzQELiKZFlH0RRXI9xsG3ErdJU3M9PcKpbGKndJ1tz92hFwy6rP1H5gwPXsx03PuiiXGGp6xZiK/BYuyzkZBjS9LRt8Z3cmjINwJSMiF8jTBfQo1sVe5eaqpDzofrCAe4VThuUsZGOpPjQsjT7xL93k8tr6soQIL8ruE6VUxscW4dAaqG+1CyRUkP8oC2SQ9TJVkYE1iI90LgwHzQEYxOzB6wwmpNZ9RM2nQ3p7eOBcn+/rbr/sc87C+exQN+lWLL32plesdVnctBxjNcfupCip66tEtx/JPqWdJvQUbRz4L2Zi2YY9wTWILn0UzIjULid6hqhe5sEoVCpjBGbCLV5E6dSRpZwsF44flLWGX5PY0nHNtE+oFReygcupxKkeOEXoFwk5GlhOzxNUGDlqWUKQuxxiGMWqmJe73hzdjUlP+VEO5dFrlQdRt4clKCZV+0kNvzxhW1GT/nxBBVermpKPIbPR019686J+pv0RFsLhZYGNGTXNc/IKCfvwhMSsF6169ue0P70AomXQXsXYNcQNAypdUGiVTIfiU6B6xVfKYKQVXu1ZqV4UxxOcSORtXAolgmGLZkc7+k8Jy8QRRY/iK3BDmsdRF2YY2p3A4=
  on:
    tags: true
    branch: master
  skip_existing: true
